### ISSUE TITLE
A ´branched´ tab seems not to invoke the TabEmptiedHandler of a custom InterTabClient

### ISSUE THREAD

**Issue by wolfmarco** [ButchersBoy/DragablzMeetzMahApps#2]
Please have a look at the ReadMe and modified example app ´OptionalCloseButton´ at:

https://github.com/wolfmarco/DragablzSamplez/tree/branched-tab-not-invokes-TabEmptiedHandler-of-custom-InterTabClient/OptionalCloseButton

A ´branched´ tab seems not to invoke the TabEmptiedHandler of a custom InterTabClient.

Is it possible to implement this?

My goal is to keep the window open after the last tab is closed independently on which window.

**Comment by ButchersBoy** [comment]
Yeah...off top of my head it must be losing that data context...i'll try and fix the demo as soon as I have chance.

In the mean time take a look at these examples in Doobry:

https://github.com/ButchersBoy/doobry/blob/master/Doobry/App.xaml.cs#L95

It's a lot easier to provide some of the callbacks as statics, to account for new windows etc.

**Comment by wolfmarco** [comment]
I do not use Dragablz anymore.
